---
title: "wk4_homework"
output: html_document
date: "2023-10-29"
---
## packages
```{r}
library(sf)
library(tidyverse)
library(here)
library(janitor)
library(tmap)
library(dplyr)

```

## read
```{r}
report <- read_csv(here::here("../giss_wk4/HDR21-22_Composite_indices_complete_time_series.csv"),
                              na= "NULL")
shape <- st_read(
  "../giss_wk4/World_Countries_Generalized/World_Countries_Generalized.shp")

```
## check out the dataset
```{r}
summary(shape)
plot(shape$geometry)

```

## task
```{r }
#create a new column for gender inequality
gender_inequality <- report %>%
  clean_names(.)%>%
  select(country,gii_2010,gii_2019) %>%
  mutate(difference=gii_2019 - gii_2010)
#report <- read_csv("../giss_wk4/HDR21-22_Composite_indices_complete_time_series.csv")
#col1 <- data$gii_2010
#col2 <- data$gii_2019
#result <- col2-col1
#write.csv(result,"result.csv")

```

## JOIN IN SPATIAL DATA
```{r}

joined_data <- gender_inequality %>% 
  clean_names(.) %>%
  left_join(., 
            shape,
            by = c("country" = "COUNTRY"))
```


